server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: zoopeer-dubbo
  redis:
    host: localhost
    port: 6379
    password: 123456a
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 300
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接
        min-idle: 8
    # 连接超时时间（毫秒）
    timeout: 12000
    database: 0